### PR TITLE
Add Xml as default response

### PR DESCRIPTION
**Pull request by litan1106**
Add Xml as default response but it can be set to array to object.

### CODE REVIEW

**Comment by tflanagan** [comment]
Just curious, what are you trying to solve here? What is requiring you to get access to the unparsed response?

**Comment by litan1106** [comment]
I think the default response as array isn't useful in a real world application. I still have to transform the array to meaningful names. Most APIs are still returning xml. Ex: Google AdWords, Google Analytics, Bing Ads, etc.

From: 
        "records": [{
            "update_id": 1440699430305,
            "rid": 4336,
            "38": 4193,
        },  {
            "update_id": 1440699430383,
            "rid": 4775,
            "38": 4640,
        }]

To: 
    "records": [{
        "id": "4336",
        "company_id": "4193",
    }, {
        "id": "4775",
        "company_id": "4640",
    }]

**Comment by tflanagan** [comment]
Hmm,

That is a pretty common function I use, I don't have the definition in front of me, but here is the basic gist:

``` php
<?php

function mapFieldKeysToRecords($records, $fields, $preserve = false){
    return array_map(function($record) use(&$fields, &$preserve){
        $field = null;

        foreach($fields as $key => $fid){
            $record[$key] = $record[$fid];

            if(!$preserve){
                unset($record[$fid]);
            }
        }

        return $record;
    }, $records);
}

// IE:
$qb = new \QuickBase\QuickBase(array(
    // ...
));

try {
    $response = $qb->api('API_DoQuery', array(
        // ...
        'clist' => '38'
    ));

    $records = mapFieldKeysToRecords($response['table']['records'], array(
        'company_id' => 38
    ));
}catch(\Exception $err){
    // Do something
}

?>
```

**Comment by litan1106** [comment]
sounds good. Thanks

**Pull request closed without merging**
